name: build

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build mplayer-ce
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout freetype
      uses: actions/checkout@master
      with:
        path: libs/freetype
    
    - name: Checkout mplayer-ce
      uses: actions/checkout@master
      with:
        path: mplayer-ce

    - name: Checkout libogc2
      uses: actions/checkout@main
      with:
        repository: emukidid/libogc
        path: libogc

    - name: add ppc gcc to PATH environment variable
      uses: myci-actions/export-env-var@1
      with:
        name: PATH
        value: $PATH:/opt/devkitpro/devkitPPC/bin

    - name: Export CFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Export CXXFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CXXFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Checkout libfat
      uses: actions/checkout@main
      with:
        repository: extremscorner/libfat
        path: libfat

    - name: Checkout devkitrice
      uses: actions/checkout@main
      with:
        repository: extremscorner/libogc-rice
        path: libogc-rice

    - name: Export DEVKITRICE
      uses: myci-actions/export-env-var@1
      with:
        name: DEVKITRICE
        value: libogc-rice

    - name: Build libogc2
      run: make install
      working-directory: libogc

    - name: Build libfat
      run: make ogc-install
      working-directory: libfat

    - name: Build mplayer
      run: |
        make -j42069
      working-directory:  mplayer-ce/mplayer

    - name: Upload mplayer-ce
      uses: actions/upload-artifact@main
      with:
        name: mplayer
        path: mplayer-ce/pack
